### ISSUE TITLE
EnumDisplaySettings function doesn't return any graphics modes

### ISSUE THREAD

**Issue by flux88** [falahati/WindowsDisplayAPI#1]
Is there a workaround to enabling an unattached display when GetPossibleSettings() doesn't return anything?

Also when the same display is enabled it correctly returns all possible display settings.

Thanks.

**Comment by flux88** [comment]
After a bit of digging I found that by switching DisplayFullName and DisplayName it works! The DisplayName is longer than DisplayFullName.
e.g. DisplayFullName is \\.\DISPLAY2
DisplayName is \\.\DISPLAY2\Monitor0

**Comment by falahati** [comment]
Meged,
Thanks.
