### ISSUE TITLE
Some fields show "Identity" instead of real value

### ISSUE THREAD

**Issue by bravo-kernel** [falahati/WindowsDisplayAPI#14]
First of all, awesome API, thank you so much ❤️.

Apologies if I'm missing something obvious here but (in some places) I'm seeing `Identity` as return value where I was expecting a value. For example like below, taken from the `WindowsDisplaySample` demo program. Using version 1.3.0.13.

All pointers appreciated.

![image](https://user-images.githubusercontent.com/230500/91199798-a9054d00-e6fe-11ea-9893-a49aa6c9ffdf.png)

**Comment by bravo-kernel** [comment]
OK, I guess it's left to the API consumer to choose whether to translate or not using e.g.

```csharp
var dpiValue = (int)WindowsDisplayAPI.Native.DisplayConfig.DisplayConfigSourceDPIScale.Identity;
```

Which produces `100` as expected.

**Comment by falahati** [comment]
I am using Enum types wherever possible instead of returning unknown numeric values. So that you can compare two values, serialize them effectively, and to know ahead of time what values are possible or to be expected. This is one of those cases.

**Comment by bravo-kernel** [comment]
Yeah, that makes total sense. Thanks for elaborating and keep up the good work !
