### ISSUE TITLE
Set Orientation?

### ISSUE THREAD

**Issue by Franck-E** [falahati/WindowsDisplayAPI#15]
More of a question than an issue, can we set the orientation?
I see the DisplayOrientation, but can we set? Or just a get?

**Comment by falahati** [comment]
You need to use the DisplayConfig set of APIs and create one or more `PathInfo` for the topology you desire and fill it with the information required. `PathTargetInfo` is another class that defines a monitor in a display config topology and its constructor accepts a value for rotation. Use that to set the orientation you want.

Otherwise you can take the current display topology and modify it and then apply it.

**Comment by Franck-E** [comment]
First of all, thank you for your reply.

Based on your comment, I can get the path like this:
var test = (from a in WindowsDisplayAPI.DisplayConfig.PathInfo.GetActivePaths(true) where a.DisplaySource.DisplayName.Contains(IoC.MainPage.SelectedDisplay.DisplayName) select a).FirstOrDefault();

but struggling with the rest. I got this which is incorrect:
WindowsDisplayAPI.DisplayConfig.PathTargetInfo pathTargetInfo = new WindowsDisplayAPI.DisplayConfig.PathTargetInfo(test, true);

**Comment by falahati** [comment]
This will modify the path information and rotate every non primary display by 180deg:

```C#
            var paths = WindowsDisplayAPI.DisplayConfig.PathInfo.GetActivePaths();
            var originalPaths = paths.ToArray();
            for (int i = 0; i < paths.Length; i++)
            {
                var path = paths[i];
                if (path.IsGDIPrimary)
                {
                    continue;
                }

                paths[i] = new PathInfo(
                    path.DisplaySource,
                    path.Position,
                    path.Resolution,
                    path.PixelFormat,
                    path.TargetsInfo.Select(
                        (t) => new PathTargetInfo(
                            t.DisplayTarget,
                            t.SignalInfo,
                            DisplayConfigRotation.Rotate180,
                            t.Scaling,
                            t.IsVirtualModeSupportedByPath
                        )
                    ).ToArray()
                );
            }

            WindowsDisplayAPI.DisplayConfig.PathInfo.ApplyPathInfos(paths);
            Console.WriteLine("Press any key to revert back.");
            Console.ReadLine();
            WindowsDisplayAPI.DisplayConfig.PathInfo.ApplyPathInfos(originalPaths);
```

**Comment by Franck-E** [comment]
This is fantastic, thank you V much.
