### ISSUE TITLE
How to get windows 10 "Active signal resolution"

### ISSUE THREAD

**Issue by sam321526** [falahati/WindowsDisplayAPI#17]
Hi All,
Is there any way to get "Active signal resolution", there is no way to get it in the WindowsDisplayAPI project
![image](https://user-images.githubusercontent.com/49781743/111242593-6e331a00-863a-11eb-8837-fab16caad23d.png)

**Comment by sam321526** [comment]
You can refer to the link, use C++ to obtain active signal resolution
https://social.msdn.microsoft.com/Forums/zh-TW/88527bc4-a2fc-405a-b3dd-ad9254da4a43/c-22914203092146224471win10?forum=233

**Comment by falahati** [comment]
Sorry for the late response.

`DisplayConfigVideoSignalInfo.ActiveSize` is the active signal resolution you are searching for. This structure is then wrapped with the `PathTargetSignalInfo` class and is accessible from the `PathTargetInfo.SignalInfo`.

**Comment by sam321526** [comment]
Yes, it work
thank you for help!!
