### ISSUE TITLE
There is a way to retrieve the display number where my app run?

### ISSUE THREAD

**Issue by Groboto** [falahati/WindowsDisplayAPI#18]
I trying to retrieve number of monitor where my wpf app is running. TIs possible to retrieve that data with  WindowsDisplayAPI?
Winform method retrieve that data, but there is no correlation on numbers with what windows display config menu show.

**Comment by falahati** [comment]
I am not sure how Windows selects these numbers, but it should be based on the order of `PathDisplaySource`s instances.  If it is not, I really have no idea how Windows decides to order display devices in Settings/Control Panel.
