### ISSUE TITLE
display.GetScreen() not available under WPF .net core ?

### ISSUE THREAD

**Issue by Franck-E** [falahati/WindowsDisplayAPI#19]
I have all references under a WPF .net core 6 project and cannot access display.GetScreen()

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows10.0.22000.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
```

Anything I am missing?

**Comment by falahati** [comment]
is this solved? if so please share the solution. if not, dont close it.
the fact that I am a little busy right now does not mean that this problem does not exist or that I am never going to investigate it.

tnx and sry

**Comment by falahati** [comment]
thank you; I have to build a separate binary for .net6 then so that I can include that part of the code. I think the released binary for net standard now does not even have that method on the compilation.
