### ISSUE TITLE
Windows 11 compatibility 

### ISSUE THREAD

**Issue by PryAl** [falahati/WindowsDisplayAPI#23]
Hi!

It seems like wrapper have some troubles with detecting displays on Win11.

`Display.GetDisplays()` returned empty collection.

Could you clarify, it is compatibility issue or it's on my side?

**Comment by falahati** [comment]
For anything over and including Win7, consider using "Windows CCD API" - `DisplayConfig` namespace. (Path, Target, Source, etc...)

For older versions, Windows CCD is not available and you have to use "Windows Display API". But it lacks a lot of features that is introduced with new versions of Windows and can't represent the real topology of screens in many cases.
