### ISSUE TITLE
Unhandled exception when desktop composition is disabled

### ISSUE THREAD

**Issue by EzeKees** [falahati/WindowsDisplayAPI#3]
Excellent library, I have used it for many months and I never had an error. Exceeding this
System.ComponentModel.Win32Exception (0x80004005): Unsupported request
   in WindowsDisplayAPI.DisplayConfig.PathInfo.GetPathInfos(QueryDeviceConfigFlags flags, DisplayConfigTopologyId& topologyId)
   in WindowsDisplayAPI.DisplayConfig.PathDisplayTarget.GetDisplayTargets()
   in ...

**Comment by falahati** [comment]
I can not test this as I am on Windows 10 and there is apparently no way to disable Windows Composition or DWM in general, in fact even killing the process just restarts it. You are probably on Win7, right?

I can't find it anywhere now, but I am pretty sure that I read somewhere in MSDN that DisplayConfig methods are dependent on the Desktop Window Manager. Therefore every class under `WindowsDisplayAPI.DisplayConfig` should be unusable when DWM is disabled. 

I suggest using other classes and methods to manage the system in similar situations, and they are also compatible with older version of Windows as well. DisplayConfig methods are only available from WinVista+.

**Comment by EzeKees** [comment]
Yes, at the time I had Windows 7 with DWM disabled. In Windows 8.1 and 10 I never had a problem because DWM can not be disabled. Thank you!

**Comment by EzeKees** [comment]
Hi, very from time to time (rarely) this error keeps happening, only on Windows 10 (DWM enabled).
Now the message is "the parameter is not correct" (0x80004005).
Could it be due to low memory?
Because on multiple PCs that have memory to spare this error does not occur. Thanks
