### ISSUE TITLE
Inlcude the "DeviceFriendlyName"

### ISSUE THREAD

**Issue by dojo90** [falahati/WindowsDisplayAPI#4]
My Setup is the following:

- Dell Precision 7510
- 2x FUJITSU E24-9 TOUCH

When using your library, I do not get "E24-9 TOUCH" as DisplayName. On stackoverflowis a solution to get this information:
- https://stackoverflow.com/a/28257839/6229375

Maybe it would be possible to retreive this information and also a display name from the internal laptop screen?

![Imgur](https://i.imgur.com/Tx7ENJp.gif)

**Comment by falahati** [comment]
The classes on the main namespace are based on "DeviceContext" set of APIs, these are more legacy and supports more systems. However, they are also old and don't provide you with much info and are not much flexible. It was a hard choice to put them in the main namespace.

The name you see there is essentially the name of the driver and in your case, your drivers are not the real display drivers so "DeviceContext" cant provide you with a name. What you want is the "FriendlyName"  of the display in the topology read from its EDID. This can be done in multiple ways.

If you are developing for Windows Vista+ or 7+ or really suggest using the "DisplayConfig" namespace altogether unless you need to work with the device context. They may seem differently named but they allow a higher degree of freedom when working with display setups. In your case, the solution might be as simple as:

```C#
display.ToPathDisplayTarget().FriendlyName
```

or you might want to use the `PathDisplayTarget` class from the beginning:

```C#
foreach (var pathDisplayTarget in PathDisplayTarget.GetDisplayTargets())
{
    Console.WriteLine(pathDisplayTarget.FriendlyName);
}
```

If you are really into extracting EDID properties tho, I suggest taking a look at my other library EDIDParser and the example provided there for extracting EDID information for a `DisplayDevice`:

```C#
byte[] edidData;
using (var key = display.OpenDevicePnPKey())
{
    using (var subkey = key.OpenSubKey("Device Parameters"))
    {
        edidData = (byte[])subkey.GetValue("EDID", null);
    }
}

var edid = new EDID(edidData);
foreach (var edidDescriptor in edid.Descriptors)
{
    if (edidDescriptor is StringDescriptor stringDescriptor && 
        stringDescriptor.Type == StringDescriptorType.MonitorName)
    {
        Console.WriteLine(stringDescriptor.Value);
        break;
    }
}
```

**Comment by dojo90** [comment]
Thanks for your reply! That work's!

**Comment by dojo90** [comment]
Thanks for your reply! That work's!
