### ISSUE TITLE
DisplayConfig ERROR_NOT_SUPPORTED - "The request is not supported exception" Windows 7

### ISSUE THREAD

**Issue by dojo90** [falahati/WindowsDisplayAPI#5]
If I run the following code on my Windows 7 virtual machine, I get the following `Exception`:

	foreach (Display display in Display.GetDisplays())
	{
		monitors.Add(new MonitorInfoViewModel(display));
	}

	public MonitorInfoViewModel(Display display)
	{
		AdapterDeviceName = display.Adapter.DeviceName;
		PreferredResolution = display.SavedSetting.Resolution;
		ActualResolution = display.CurrentSetting.Resolution;

		FriendlyName = display.ToPathDisplayTarget().FriendlyName;
	}

> Message 'Die Anforderung wird nicht unterstützt' StackTrace '   bei WindowsDisplayAPI.DisplayConfig.PathInfo.GetPathInfos(QueryDeviceConfigFlags flags, DisplayConfigTopologyId& topologyId)
   bei WindowsDisplayAPI.DisplayConfig.PathDisplayTarget.GetDisplayTargets()
   bei WindowsDisplayAPI.DisplayDevice.ToPathDisplayTarget()

![system](https://i.imgur.com/40e9IWr.png)

![oracle](https://i.imgur.com/WNdMH7k.png)

**Comment by falahati** [comment]
This is documented behaviour. DisplayConfig set of APIs is only supported on devices with a compatible WMMD driver. 

https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-querydisplayconfig

> **ERROR_NOT_SUPPORTED** 
> The system is not running a graphics driver that was written according to the Windows Display Driver Model (WDDM). The function is only supported on a system with a WDDM driver running.

Try installing [Guest Additions for Windows](http://download.virtualbox.org/virtualbox/5.2.22/VBoxGuestAdditions_5.2.22.iso) and try again.

**Comment by dojo90** [comment]
Thanks for your answer!
I have solved it by using a `try{}catch{}` block.
