### ISSUE TITLE
Error getting monitor friendly names when using remote desktop

### ISSUE THREAD

**Issue by gaurav110** [falahati/WindowsDisplayAPI#6]
Error Message:The parameter is incorrect. 
Trace:    at WindowsDisplayAPI.DisplayConfig.PathInfo.GetPathInfos(QueryDeviceConfigFlags flags, DisplayConfigTopologyId& topologyId)
   at WindowsDisplayAPI.DisplayConfig.PathDisplayTarget.GetDisplayTargets()
   at Application1.Helper.ScreenHelper.GetScreenList() in c:\agent\_work\2\s\Application1\Main\ScreenList\Helper\ScreenHelper.cs:line 21

**Comment by falahati** [comment]
To be clear, you get the same exception if you run `PathInfo.GetAllPaths()`? What about `PathInfo.GetActivePaths()` or `PathInfo.GetCurrentDatabasePaths()`?

**Comment by falahati** [comment]
This seems identical to this:
https://stackoverflow.com/questions/25976630/changedisplaysettings-fails-when-try-to-acess-remoting

It seems that Display Mirror drivers are not very `DisplayConfig` friendly. For more information about RDP display driver see this link: https://docs.microsoft.com/en-us/windows-hardware/drivers/display/remote-display-drivers

RemoteFX might or might not help; however, to be able to enable RemoteFX your host OS needs to meet the following requirements:

* Windows Server 2016 or Windows 10
* DX 11.0 compatible GPU with WDDM 1.2 compatible driver
* Windows Server RD Virtualization Host role enabled (enables Hyper-V Role)
* Server with a CPU that supports SLAT (Second Level Address Translation)

For more information regarding RemoteFX you can check this link:
https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-remotefx-vgpu


I am going to close this issue as this is a problem with underlying Windows API and does not have anything to do with this library, however, if anyone managed to have it working using RemoteFX it would be great to report here.
