### ISSUE TITLE
Library does not allow for serialization to file

### ISSUE THREAD

**Issue by xantari** [falahati/WindowsDisplayAPI#7]
Hi,

This library has issues dumping all of the data to an XML file because it can't be serialized due to many of the classes not having parameterless constructors.

I've fixed this and will do a pull request shortly.

Thanks for a great library!

**Comment by xantari** [comment]
Disregard, the built in XMLSerializer blows.

Just reverted to the Newtonsoft using this code:

```cs
JsonSerializer serializer = new JsonSerializer();
serializer.Converters.Add(new JavaScriptDateTimeConverter());
serializer.NullValueHandling = NullValueHandling.Ignore;
serializer.Formatting = Formatting.Indented;
serializer.Error += Serializer_Error; //Ignore errors
using (StreamWriter sw = new StreamWriter(filePath, false))
using (JsonWriter writer = new JsonTextWriter(sw))
{
	serializer.Serialize(writer, _displayDetails);
}
```

**Comment by falahati** [comment]
You should consider creating a `Model` class for storing, loading and transferring data. Classes of this library are not created to be serializable and there is no guarantee for them to work as expected when deserialized forcefully.

**Comment by xantari** [comment]
@falahati Thanks! I only need to dump the information from both the EDIDParser library you created as well as this library and Newtonsoft worked perfectly. Don't need to reload anything, it was really for debug purposes. I am using it in this program if your interested: https://github.com/xantari/PinCabScreenConfigurator
